### ISSUE TITLE
Add pypi badge to readme

### ISSUE THREAD

**Issue by robmarkcole** [earthdaily/earthdaily-python-client#107]
At head of readme:

[![PyPI Version](https://img.shields.io/pypi/v/earthdaily.svg)](https://pypi.org/project/earthdaily/)

**Comment by robmarkcole** [comment]
I see one exists, but is incorrect:

![image](https://github.com/user-attachments/assets/9d653c8d-63d5-443e-b068-7e3144bdd190)

**Comment by nkarasiak** [comment]
It's a caching issue, so no issue :)
