### ISSUE TITLE
ValueError: chunks keys ('y', 'x') not found in data dimensions ('latitude', 'longitude', 'time')

### ISSUE THREAD

**Issue by robmarkcole** [earthdaily/earthdaily-python-client#110]
Search of 
```python
datacube = earthdaily.earthdatastore.datacube(
    items, 
    intersects=pivot, 
    assets=["blue", "green", "red", "nir"],
    resolution=10,
    crs="EPSG:4326",
).load()
```
Returns error:
```
ValueError: chunks keys ('y', 'x') not found in data dimensions ('latitude', 'longitude', 'time')
```
Reason: `EPSG:4326` has no x,y dimensions, only latitude and longitude for odc stac. But Earthdaily is searching for x and y.

Workaround: use `EPSG:3857`

**Comment by robmarkcole** [comment]
The error is cleared but I have a different error - `NoDataInBounds` but this query is validated with 3857
```
import earthdaily

datacube = earthdaily.earthdatastore.datacube(
    items, 
    bbox=bbox,
    assets=["blue", "green", "red", "nir"],
    resolution=10,
    crs="EPSG:4326", # Error NoDataInBounds: No data found in bounds. Data variable: blue
    # crs="epsg:3857",  # Works, 7.2 sec
)
```

**Comment by nkarasiak** [comment]
Fixed by converting latitude/longittude to y,x. Can you confirm @robmarkcole  ?

**Comment by robmarkcole** [comment]
My bbox - `bbox = [-55.57156688186254, -13.036094955921214, -55.5165546572249, -12.991699609079191] ` should it be converted? Would it be safer just to accept a gdf?

**Comment by nkarasiak** [comment]
Eum seems ok, as I cannot reproduce, difficult to answer.

**Comment by robmarkcole** [comment]
Will create a fresh issue if I can create a reproducible example on public data
